// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQXx8tVmc6QwWtlC7AHwBozfnJIRV91Nw',
    appId: '1:351272245845:web:f1816adc539684ebb692dc',
    messagingSenderId: '351272245845',
    projectId: 'shopping-list-ef7c2',
    authDomain: 'shopping-list-ef7c2.firebaseapp.com',
    storageBucket: 'shopping-list-ef7c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAVsAr0XBX5GCOtNVGoE_J9DfP1TSvPQg',
    appId: '1:351272245845:android:452e5b3069f98d68b692dc',
    messagingSenderId: '351272245845',
    projectId: 'shopping-list-ef7c2',
    storageBucket: 'shopping-list-ef7c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUqtWBbmCpuLnhRTtb0dEliY2iKHvwQ2U',
    appId: '1:351272245845:ios:47045d260f903f2ab692dc',
    messagingSenderId: '351272245845',
    projectId: 'shopping-list-ef7c2',
    storageBucket: 'shopping-list-ef7c2.appspot.com',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUqtWBbmCpuLnhRTtb0dEliY2iKHvwQ2U',
    appId: '1:351272245845:ios:fe5117008eaf7be0b692dc',
    messagingSenderId: '351272245845',
    projectId: 'shopping-list-ef7c2',
    storageBucket: 'shopping-list-ef7c2.appspot.com',
    iosBundleId: 'com.example.shoppingList.RunnerTests',
  );
}
